Poc/new theme
WeAreSnook/cyber-health-frontend pull request #94
Opened 2021-05-17 15:52 UTC by adamgparsons

- adds gds style theme to django admin
- Migration and fixture included

2021-05-17 16:04 UTC, kingdomlevel approved these changes
Looks good!

2021-05-17 16:18 UTC, kingdomlevel requested changes
Actually, the build failed! Un-approving for now...

2021-05-17 16:25 UTC, kingdomlevel commented
From Adam:

1. Hard code whatever the mixins are doing
2. import the mixins into each SCSS file that it's being used

Option 2 is probably preferred here

2021-05-17 16:45 UTC, adamgparsons commented
Just completed option 2 "import the mixins into each SCSS file that it's being used" and looks like the travis is passing the build. May need another review

2021-05-18 08:05 UTC, kingdomlevel reviewed
It looks good to me! Running the build on Travis one more time for good luck...

2021-05-18 08:15 UTC, kingdomlevel approved these changes

2021-05-18 08:32 UTC, merged